# Generated by Django 5.1.5 on 2025-01-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="mobile",
            new_name="contact_no",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="address",
            new_name="father_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
        migrations.AddField(
            model_name="employee",
            name="current_address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="employee",
            name="current_job",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="dob",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Male",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                ],
                default="Single",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="permanent_address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="employee",
            name="previous_job",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="previous_job_duration",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="religious",
            field=models.CharField(
                choices=[
                    ("Islam", "Islam"),
                    ("Christianity", "Christianity"),
                    ("Hinduism", "Hinduism"),
                    ("Sikhism", "Sikhism"),
                    ("Judaism", "Judaism"),
                    ("Buddhism", "Buddhism"),
                    ("Other", "Other"),
                ],
                default="Islam",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="cnic",
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
    ]
