# Generated by Django 5.1.5 on 2025-01-28 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("departments", "0001_initial"),
        ("employees", "0002_rename_mobile_employee_contact_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="previous_job",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="previous_job_duration",
        ),
        migrations.AddField(
            model_name="employee",
            name="previous_job_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="previous_job_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="previous_job_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="cnic",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="contact_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="current_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="current_job",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="departments.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="father_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="permanent_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="religious",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
