# Generated by Django 5.1.5 on 2025-02-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_remove_employee_previous_job_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="face_encoding",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
