# Generated by Django 5.1.6 on 2025-03-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0004_employee_face_encoding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="face_encoding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
