# Generated by Django 5.1.6 on 2025-03-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0005_alter_employee_face_encoding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
