# Generated by Django 5.1.6 on 2025-03-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0006_alter_employee_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="face_encoding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
