# Generated by Django 5.1.7 on 2025-04-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "employees",
            "0008_remove_employee_face_encoding_employee_annual_leave_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Others", "Others")],
                default="Male",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Married", "Married"),
                    ("Divorced", "Divorced"),
                    ("Widowed", "Widowed"),
                ],
                default="Single",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="religious",
            field=models.CharField(
                choices=[
                    ("Islam", "Islam"),
                    ("Christianity", "Christianity"),
                    ("Hinduism", "Hinduism"),
                    ("Others", "Others"),
                ],
                default="Islam",
                max_length=20,
            ),
        ),
    ]
