# Generated by Django 5.1.7 on 2025-04-21 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "employees",
            "0009_alter_employee_gender_alter_employee_marital_status_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="stauts",
            new_name="status",
        ),
    ]
