# Generated by Django 5.1.6 on 2025-02-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ogp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ogpitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
