# Generated by Django 5.1.5 on 2025-01-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[("admin", "Admin"), ("hr", "HR"), ("staff", "Staff")],
                default="staff",
                max_length=50,
            ),
        ),
    ]
