# Generated by Django 5.1.5 on 2025-02-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_item_item_no_alter_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_no",
            field=models.CharField(
                db_index=True, default=0, max_length=50, unique=True
            ),
        ),
    ]
