# Generated by Django 5.1.5 on 2025-01-24 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("igp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="igpitem",
            name="igp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="igp.igp",
            ),
        ),
    ]
