# Generated by Django 5.1.5 on 2025-02-11 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("igp", "0003_igp_created_at_igp_created_by_igp_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="igp",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="igp",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="igp",
            name="status",
        ),
        migrations.RemoveField(
            model_name="igp",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="igp",
            name="updated_by",
        ),
    ]
