# Generated by Django 5.1.5 on 2025-02-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("igp", "0004_remove_igp_created_at_remove_igp_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="igpitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
