# Generated by Django 5.1.7 on 2025-04-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("igp", "0006_igp_created_at_igp_created_by_igp_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="igp",
            name="igp_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
