# Generated by Django 5.1.5 on 2025-02-01 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AttendanceSettings",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="date",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="is_early_leave",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="is_late",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="total_hours",
        ),
        migrations.AddField(
            model_name="attendance",
            name="attendance_date",
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name="attendance",
            name="break_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="break_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="status",
            field=models.CharField(default="Present", max_length=10),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_in",
            field=models.TimeField(default=datetime.time(11, 26, 5, 65593)),
        ),
    ]
