# Generated by Django 5.1.7 on 2025-04-21 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="attendance_type",
            field=models.CharField(
                choices=[
                    ("Check In", "Check In"),
                    ("Check Out", "Check Out"),
                    ("Break Out", "Break Out"),
                    ("Break In", "Break In"),
                    ("For Market", "For Market"),
                    ("From Market", "From Market"),
                    ("For Vendor", "For Vendor"),
                    ("From Vendor", "From Vendor"),
                ],
                default="Check In",
                max_length=50,
            ),
        ),
    ]
