# Generated by Django 5.1.5 on 2025-02-03 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "attendance",
            "0002_delete_attendancesettings_remove_attendance_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_in",
            field=models.TimeField(default=datetime.time(11, 2, 27, 618502)),
        ),
    ]
