# Generated by Django 5.1.7 on 2025-04-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_attendance_date_alter_attendance_attendance_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="late_minutes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
