# Generated by Django 5.1.7 on 2025-04-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_attendance_created_at_attendance_late_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("Present", "Present"),
                    ("Absent", "Absent"),
                    ("Leave", "Leave"),
                ],
                default="Absent",
                max_length=50,
            ),
        ),
    ]
