# Generated by Django 5.1.7 on 2025-04-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0004_attendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
