# Generated by Django 5.1.5 on 2025-02-11 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0005_alter_attendance_check_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_in",
            field=models.TimeField(default=datetime.time(11, 4, 8, 19227)),
        ),
    ]
