# Generated by Django 5.1.6 on 2025-02-18 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0007_alter_attendance_check_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_in",
            field=models.TimeField(default=datetime.time(9, 35, 19, 367397)),
        ),
    ]
